# Generated by Django 5.1.6 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='黄金代码', max_length=10)),
                ('name', models.CharField(help_text='黄金名称', max_length=50)),
                ('time', models.DateTimeField(help_text='时间')),
                ('price', models.DecimalField(decimal_places=2, help_text='价格', max_digits=10)),
                ('open', models.DecimalField(decimal_places=2, help_text='开盘价', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='最高价', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='最低价', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='收盘价', max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, help_text='涨跌额', max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, help_text='涨跌幅', max_digits=10)),
            ],
            options={
                'db_table': 'gold_index',
                'indexes': [models.Index(fields=['symbol', 'time'], name='gold_index_symbol_3d20b9_idx')],
                'unique_together': {('symbol', 'time')},
            },
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='指数代码', max_length=10)),
                ('market', models.CharField(help_text='市场代码', max_length=10)),
                ('name', models.CharField(help_text='指数名称', max_length=50)),
                ('time', models.DateTimeField(help_text='时间')),
                ('open', models.DecimalField(decimal_places=2, help_text='开盘价', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='最高价', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='最低价', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='收盘价', max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, help_text='成交量', max_digits=20)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'market_index',
                'indexes': [models.Index(fields=['market', 'symbol', 'time'], name='market_inde_market_c53c8b_idx')],
                'unique_together': {('symbol', 'time')},
            },
        ),
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'stock_quote',
                'indexes': [models.Index(fields=['symbol', 'time'], name='stock_quote_symbol_fd9006_idx')],
            },
        ),
    ]
